name: ML Pipeline CI

on:
  # push:
  #   branches: [ main, master  ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4 # PRのコードをチェックアウト (v3からv4に更新)
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov mlflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Checkout baseline model from main branch
      uses: actions/checkout@v4 # ベースラインモデル取得のために再度チェックアウト
      with:
        ref: main # ベースラインとするブランチ (mainまたはmasterなど)
        path: .baseline_checkout # 一時的なディレクトリにチェックアウト
        sparse-checkout: |       # 必要なファイルのみを効率的にチェックアウト
          day5/演習1/models/titanic_model.pkl

    - name: Setup baseline model for test
      run: |
        BASELINE_MODEL_SOURCE_PATH=".baseline_checkout/day5/演習1/models/titanic_model.pkl"
        BASELINE_MODEL_TARGET_DIR="day5/演習1/models"
        
        mkdir -p $BASELINE_MODEL_TARGET_DIR 
        if [ -f "$BASELINE_MODEL_SOURCE_PATH" ]; then
          cp "$BASELINE_MODEL_SOURCE_PATH" "$BASELINE_MODEL_TARGET_DIR/"
          echo "INFO: Baseline model 'titanic_model.pkl' copied to $BASELINE_MODEL_TARGET_DIR/" 
        else
          echo "WARN: Baseline model not found at $BASELINE_MODEL_SOURCE_PATH. Regression test might fail if the test strictly requires it."
          # test_model.py内のテストはファイルが存在しない場合 pytest.fail するため、ここでexit 1しなくてもテストは失敗する
        fi
        
    - name: Lint with flake8
      run: |
        flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        
    - name: Format check with black
      run: |
        black --check day5/演習3
        
    - name: Run data tests
      run: |
        pytest day5/演習3/tests/test_data.py -v
        
    - name: Run model tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "INFO: Starting model regression test against baseline file."
        pytest day5/演習3/tests/test_model.py -k test_model_regression_against_baseline_file -v
        PYTEST_EXIT_CODE=$?
        echo "INFO: Pytest execution finished with exit code $PYTEST_EXIT_CODE."
        exit $PYTEST_EXIT_CODE